import { ImageMetadata, ImageRank } from '@rankle/shared/data-models';

export const IMAGES: (ImageMetadata & Record<string, any>)[] = [
  {
    _job_type: 'diffusion_upsample_v5_virtual',
    _parsed_params: {
      aspect: '16:9',
      creative: false,
      fast: false,
      hd: false,
      niji: false,
      no: [],
      style: '',
      test: false,
      testp: false,
      tile: false,
      upanime: false,
      upbeta: false,
      uplight: false,
      version: 5,
      vibe: false,
      video: false,
    },
    _service: 'main',
    avatar_job_id: 'baec62ec-7d4d-4d70-89f7-66477a9d5eb5',
    cover_job_id: 'b02c50da-1082-4569-a8bd-4a219b33372c',
    current_status: 'completed',
    enqueue_time: '2023-04-22 22:10:46.670964',
    event: {
      height: 816,
      textPrompt: [
        'Movie still from "The Castle of Books", a retro fantasy film with low production cost. Closeup shot on the main character. 1970s Aesthetic. Costumes with feather accents and bright colors. Magic in the air, sparkles and flashes of light.',
      ],
      imagePrompts: null,
      width: 1456,
      batchSize: 1,
      seedImageURL: 'https://storage.googleapis.com/dream-machines-output/c3f9544f-7ea0-4d91-87d5-6b92f495016a/0_2.png',
      textPromptWeights: [1],
      eventType: 'upscale',
      test: false,
    },
    flagged: false,
    full_command:
      'Movie still from "The Castle of Books", a retro fantasy film with low production cost. Closeup shot on the main character. 1970s Aesthetic. Costumes with feather accents and bright colors. Magic in the air, sparkles and flashes of light. --ar 16:9 --v 5',
    grid_cells: 0,
    grid_id: null,
    grid_num: null,
    guild_id: '1046552914921005076',
    hidden: false,
    id: '9cea903a-f374-468e-80bb-6acd8cef9ce2',
    image_paths: ['https://storage.googleapis.com/dream-machines-output/c3f9544f-7ea0-4d91-87d5-6b92f495016a/0_2.png'],
    is_published: true,
    liked_by_user: false,
    liked_timestamp: null,
    low_priority: false,
    metered: false,
    mod_hidden: false,
    parent_grid: 2,
    parent_id: 'c3f9544f-7ea0-4d91-87d5-6b92f495016a',
    parsed_command: null,
    platform: 'discord',
    platform_channel: 'Untracked',
    platform_channel_id: '1052138700278087680',
    platform_message_id: '1099457316950134884',
    platform_thread_id: null,
    prompt:
      'Movie still from "The Castle of Books", a retro fantasy film with low production cost. Closeup shot on the main character. 1970s Aesthetic. Costumes with feather accents and bright colors. Magic in the air, sparkles and flashes of light.',
    ranked_by_user: false,
    ranked_timestamp: null,
    ranking_by_user: null,
    reference_image_num: '2',
    reference_job_id: 'c3f9544f-7ea0-4d91-87d5-6b92f495016a',
    soft_ban: false,
    tag: null,
    trial: false,
    type: 'v5_upscale',
    user_id: '7f7106e8-0bdf-4077-ab3d-e5b23c69f47a',
    username: 'evanfuture',
  },
  {
    _job_type: 'diffusion_upsample_v5_virtual',
    _parsed_params: {
      aspect: '16:9',
      creative: false,
      fast: false,
      hd: false,
      niji: false,
      no: [],
      style: '',
      test: false,
      testp: false,
      tile: false,
      upanime: false,
      upbeta: false,
      uplight: false,
      version: 5,
      vibe: false,
      video: false,
    },
    _service: 'main',
    avatar_job_id: 'baec62ec-7d4d-4d70-89f7-66477a9d5eb5',
    cover_job_id: 'b02c50da-1082-4569-a8bd-4a219b33372c',
    current_status: 'completed',
    enqueue_time: '2023-04-22 22:02:38.135039',
    event: {
      height: 816,
      textPrompt: [
        'Movie still from "The Castle of Books", a retro fantasy film with low production cost. Closeup shot on the main character. 1980s Aesthetic. Costumes with feather accents and bright colors. Magic in the air, sparkles and flashes of light.',
      ],
      imagePrompts: null,
      width: 1456,
      batchSize: 1,
      seedImageURL: 'https://storage.googleapis.com/dream-machines-output/6c171a5b-3330-4b05-b0a2-49f2f5932f72/0_2.png',
      textPromptWeights: [1],
      eventType: 'upscale',
      test: false,
    },
    flagged: false,
    full_command:
      'Movie still from "The Castle of Books", a retro fantasy film with low production cost. Closeup shot on the main character. 1980s Aesthetic. Costumes with feather accents and bright colors. Magic in the air, sparkles and flashes of light. --ar 16:9 --v 5',
    grid_cells: 0,
    grid_id: null,
    grid_num: null,
    guild_id: '1046552914921005076',
    hidden: false,
    id: 'e9a9b197-18cc-4bec-bd33-eb3d6c76d141',
    image_paths: ['https://storage.googleapis.com/dream-machines-output/6c171a5b-3330-4b05-b0a2-49f2f5932f72/0_2.png'],
    is_published: true,
    liked_by_user: false,
    liked_timestamp: null,
    low_priority: false,
    metered: false,
    mod_hidden: false,
    parent_grid: 2,
    parent_id: '6c171a5b-3330-4b05-b0a2-49f2f5932f72',
    parsed_command: null,
    platform: 'discord',
    platform_channel: 'Untracked',
    platform_channel_id: '1052138700278087680',
    platform_message_id: '1099455264073187339',
    platform_thread_id: null,
    prompt:
      'Movie still from "The Castle of Books", a retro fantasy film with low production cost. Closeup shot on the main character. 1980s Aesthetic. Costumes with feather accents and bright colors. Magic in the air, sparkles and flashes of light.',
    ranked_by_user: false,
    ranked_timestamp: null,
    ranking_by_user: null,
    reference_image_num: '2',
    reference_job_id: '6c171a5b-3330-4b05-b0a2-49f2f5932f72',
    soft_ban: false,
    tag: null,
    trial: false,
    type: 'v5_upscale',
    user_id: '7f7106e8-0bdf-4077-ab3d-e5b23c69f47a',
    username: 'evanfuture',
  },
];

export const RANKINGS: ImageRank[] = IMAGES.map(i => {
  return {
    id: i.id,
    capture_time: i.enqueue_time,
    elo_rating: 1200,
  };
});
